### ISSUE TITLE
STK Push

### ISSUE THREAD

**Issue by maukoese** [kopokopo/k2-connect-php#1]
When will STK Push be ready for use? A lot of clients using your till numbers would like to have STK Push implemented on their website.

**Comment by NicolletNjora** [comment]
> When will STK Push be ready for use? A lot of clients using your till numbers would like to have STK Push implemented on their website.

@maukoese We are working on launching it soon. In the meantime, you can access our [**sandbox**](https://sandbox.kopokopo.com) for development purposes.
