### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Kopokopo\SDK\K2::initiateIncomingPayment()

### ISSUE THREAD

**Issue by britisharmy** [kopokopo/k2-connect-php#25]
I have the following code from the docs

I have installed the php package from composer using

```composer require kopokopo/k2-connect-php```

and this is the code

```
<?php
use Kopokopo\SDK\K2;

require 'vendor/autoload.php';


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


$options = [
    'clientId' => '', 
    'clientSecret' => '',
    'apiKey' => '',
    'baseUrl' => 'https://api.kopokopo.com'
];

$stk = new K2($options);

$response = $stk->initiateIncomingPayment([
  'paymentChannel' => 'M-PESA STK Push',
  'tillNumber' => '',
  'firstName' => '',
  'lastName' => '',
  'phoneNumber' => '',
  'amount' => 1,
  'currency' => 'KES',
  'email' => '@gmail.com',
  'callbackUrl' => '',
  'accessToken' => '',
]);

if($response['status'] == 'success')
{
    echo "The resource location is:" . json_encode($response['location']);
}
```

but i keep getting this error

Fatal error: Uncaught Error: Call to undefined method Kopokopo\SDK\K2::initiateIncomingPayment() in /var/www/html/stk.php:21

**Comment by NicolletNjora** [comment]
@britisharmy you are supposed to initialise the STKService using an initialised K2 instance. Below is a screenshot from the repo's README.

![image](https://user-images.githubusercontent.com/59557529/186150028-56ebcd2a-927c-4854-be7d-158a6ab353a4.png)

**Comment by britisharmy** [comment]
I have made amends and my code looks like this

```
<?php
use Kopokopo\SDK\K2;

require 'vendor/autoload.php';


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


$options = [
    'clientId' => '', 
    'clientSecret' => '',
    'apiKey' => '',
    'baseUrl' => 'https://api.kopokopo.com'
];

$stk = new K2($options);
$mpesa = $stk->StkService();
$response = $mpesa->initiateIncomingPayment([
  'paymentChannel' => 'M-PESA STK Push',
  'tillNumber' => '',
  'firstName' => '',
  'lastName' => '',
  'phoneNumber' => '',
  'amount' => 100,
  'currency' => 'KES',
  'email' => '',
  'callbackUrl' => '',
  'accessToken' => '',
]);

if($response['status'] == 'success')
{
    echo "The resource location is:" . json_encode($response['location']);
}
```

However i still cannot trigger stk push on customers phone.

**Comment by NicolletNjora** [comment]
@britisharmy This is an issue with your implementation and not the SDK itself. You are only echoing if the response is successful so how would you know what error is being returned if you aren't printing it? Also, please note that you should be using the sandbox for development purposes, not production.

 You can start by using postman requests so that you can troubleshoot and see where you are going wrong. You can also join discord and get help from the community using the following link: https://discord.gg/gjJyjjWvG9 
 
Kindly note that there is already vast documentation that you are not utilising as there is a whole example app that shows how to use the SDK and 3 other documentations that cover the same. Ensure you read it properly before opening issues so that this platform is left open for actual issues with the SDK.

**Comment by britisharmy** [comment]
There is a lot to unpack here but lets start with the fact that this repo is broken and composer and git and sometimes even throws curl errors. 

Today since the physical till was delivered to my office, call after call all you had for me is RTFM which is rather telling. The physical document with the TOS that you delivered on clause 9  does not complete the sentence which is comical for all the calls telling me to go read the manual.

Also, there was no way of knowing that there is a separate till number that starts with K. No docs for that as well. If you know where that is, point it here with a  link. There is no word on rate limits for the API push.

Kindly show me the "whole example" you talk of. Anyways, today was a wasted day, no truck left our facilities thanks to your generous vast documentation that "clearly" efficient in teaching how to use the API.

I have successfully managed to get it working and i never once looked at your  "working application" or whatever its being called.

For anyone else who may need it here it is https://gist.github.com/britisharmy/0fdd58919192d21795b22eaaf0810e78


I like KopoKopo service but you should consider having paid support if at all someone wants prompt technical assistance.
