### ISSUE TITLE
composer cant find package

### ISSUE THREAD

**Issue by abiudeko** [kopokopo/k2-connect-php#3]
[InvalidArgumentException]
  Could not find a matching version of package kopokopo/k2-connect-php. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

Kindly assist.

**Comment by NicolletNjora** [comment]
@abiudeko, the package is not yet published. Please check again before the end of the week.

**Comment by NicolletNjora** [comment]
@abiudeko, the package has been published.  Let me know if you encounter any issues.
