### ISSUE TITLE
Error Testing with provided incoming payment Payload

### ISSUE THREAD

**Issue by kamnjoro** [kopokopo/k2-connect-php#7]
The example given in https://api-docs.kopokopo.com/?php#process-incoming-payment-result for the PhP version is unparsable.
It is neither Json(even though header claims to be application/json) nor an array. While trying to parse it as array it leads it leads to the error " Illegal string offset" ***.

**Comment by NicolletNjora** [comment]
@kamnjoro, is this with version 1.1.0? There were some bugs that were reported with the first version but the latest version fixed them. Could you confirm what version of the SDK you are using?

**Comment by kamnjoro** [comment]
I just run composer require kopokopo/k2-connect-php afresh
Cannot tell what SDK version is in use

**Comment by NicolletNjora** [comment]
You can check the version on the composer.json file. Also, what framework are you using?

**Comment by kamnjoro** [comment]
I run Codeigniter

**Comment by kamnjoro** [comment]
Some errors my team and I get during the testing phase are no where documented.
I am able to easily get an access token. However, hitting the initiateIncomingPayment endpoint with the required options returns an empty error response shown below
{"status":"error","data":{"errorCode":null,"errorMessage":null}}
Here is my composer file
{
    "require": {
        "kopokopo/k2-connect-php": "^1.1"
    }
}

**Comment by NicolletNjora** [comment]
I am looking into this.

**Comment by fabianmuema** [comment]
Any solutions on this

**Comment by NicolletNjora** [comment]
That error occurs when a wrong base url is being used. Confirm that you are using api.kopokopo.com instead of app.kopokopo.com
